# Generated by Django 5.1.2 on 2024-11-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='political_party',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_id_proof',
            field=models.FileField(blank=True, null=True, upload_to='user_ids/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
