# Generated by Django 5.1.2 on 2024-11-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_userprofile_political_party_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='custom_user_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_id_proof',
            field=models.CharField(max_length=100),
        ),
    ]
