# Generated by Django 5.1.2 on 2024-11-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofile_custom_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='custom_user_id',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='No name', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='political_party',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_id_proof',
            field=models.FileField(upload_to='user_id_proofs/'),
        ),
    ]
