# Generated by Django 5.1.2 on 2024-11-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_userprofile_custom_user_id_userprofile_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='political_party',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='father_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_id_proof',
            field=models.FileField(upload_to='id_proofs/'),
        ),
    ]
