# Generated by Django 5.1.2 on 2024-11-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_userprofile_address_alter_userprofile_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='political_party',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
