# Generated by Django 5.1.2 on 2024-11-09 11:34

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userprofile_political_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', validators=[users.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='political_party',
            field=models.CharField(blank=True, choices=[('BJP', 'Bharatiya Janata Party (BJP)'), ('INC', 'Indian National Congress (INC)'), ('AAP', 'Aam Aadmi Party (AAP)'), ('NCP', 'Nationalist Congress Party (NCP)'), ('SS', 'Shiv Sena'), ('SP', 'Samajwadi Party (SP)'), ('IUML', 'Indian Union Muslim League (IUML)'), ('PDP', 'Jammu & Kashmir Peoples Democratic Party (PDP)')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_id_proof',
            field=models.FileField(blank=True, null=True, upload_to='id_proofs/', validators=[users.models.validate_file_size]),
        ),
    ]
