# Generated by Django 5.1.2 on 2024-11-11 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_userprofile_is_complete_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='political_party',
        ),
    ]
