# Generated by Django 5.1.2 on 2024-11-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_userprofile_political_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
